services:
  - type: web
    name: ambiora-esports-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CLIENT_ORIGIN
        sync: false
